### YamlMime:ManagedReference
items:
- uid: CampusCrafterTests.ReviewApplicationTests
  commentId: T:CampusCrafterTests.ReviewApplicationTests
  id: ReviewApplicationTests
  parent: CampusCrafterTests
  children:
  - CampusCrafterTests.ReviewApplicationTests.Setup
  - CampusCrafterTests.ReviewApplicationTests.WhenAllScholarlyAchievementsAreScored_ThenApplicationCanBeAccepted
  - CampusCrafterTests.ReviewApplicationTests.WhenNotAllScholarlyAchievementsAreScored_ThenApplicationCannotBeAccepted
  langs:
  - csharp
  - vb
  name: ReviewApplicationTests
  nameWithType: ReviewApplicationTests
  fullName: CampusCrafterTests.ReviewApplicationTests
  type: Class
  source:
    remote:
      path: CampusCrafterTests/ReviewApplicationTests.cs
      branch: monczak
      repo: https://github.com/CampusCrafter/campuscrafter
    id: ReviewApplicationTests
    path: CampusCrafterTests/ReviewApplicationTests.cs
    startLine: 9
  assemblies:
  - CampusCrafterTests
  namespace: CampusCrafterTests
  syntax:
    content: public class ReviewApplicationTests
    content.vb: Public Class ReviewApplicationTests
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: CampusCrafterTests.ReviewApplicationTests.Setup
  commentId: M:CampusCrafterTests.ReviewApplicationTests.Setup
  id: Setup
  parent: CampusCrafterTests.ReviewApplicationTests
  langs:
  - csharp
  - vb
  name: Setup()
  nameWithType: ReviewApplicationTests.Setup()
  fullName: CampusCrafterTests.ReviewApplicationTests.Setup()
  type: Method
  source:
    remote:
      path: CampusCrafterTests/ReviewApplicationTests.cs
      branch: monczak
      repo: https://github.com/CampusCrafter/campuscrafter
    id: Setup
    path: CampusCrafterTests/ReviewApplicationTests.cs
    startLine: 75
  assemblies:
  - CampusCrafterTests
  namespace: CampusCrafterTests
  syntax:
    content: >-
      [SetUp]

      public Task Setup()
    return:
      type: System.Threading.Tasks.Task
    content.vb: >-
      <SetUp>

      Public Function Setup() As Task
  overload: CampusCrafterTests.ReviewApplicationTests.Setup*
  attributes:
  - type: NUnit.Framework.SetUpAttribute
    ctor: NUnit.Framework.SetUpAttribute.#ctor
    arguments: []
- uid: CampusCrafterTests.ReviewApplicationTests.WhenAllScholarlyAchievementsAreScored_ThenApplicationCanBeAccepted
  commentId: M:CampusCrafterTests.ReviewApplicationTests.WhenAllScholarlyAchievementsAreScored_ThenApplicationCanBeAccepted
  id: WhenAllScholarlyAchievementsAreScored_ThenApplicationCanBeAccepted
  parent: CampusCrafterTests.ReviewApplicationTests
  langs:
  - csharp
  - vb
  name: WhenAllScholarlyAchievementsAreScored_ThenApplicationCanBeAccepted()
  nameWithType: ReviewApplicationTests.WhenAllScholarlyAchievementsAreScored_ThenApplicationCanBeAccepted()
  fullName: CampusCrafterTests.ReviewApplicationTests.WhenAllScholarlyAchievementsAreScored_ThenApplicationCanBeAccepted()
  type: Method
  source:
    remote:
      path: CampusCrafterTests/ReviewApplicationTests.cs
      branch: monczak
      repo: https://github.com/CampusCrafter/campuscrafter
    id: WhenAllScholarlyAchievementsAreScored_ThenApplicationCanBeAccepted
    path: CampusCrafterTests/ReviewApplicationTests.cs
    startLine: 85
  assemblies:
  - CampusCrafterTests
  namespace: CampusCrafterTests
  syntax:
    content: >-
      [Test]

      public Task WhenAllScholarlyAchievementsAreScored_ThenApplicationCanBeAccepted()
    return:
      type: System.Threading.Tasks.Task
    content.vb: >-
      <Test>

      Public Function WhenAllScholarlyAchievementsAreScored_ThenApplicationCanBeAccepted() As Task
  overload: CampusCrafterTests.ReviewApplicationTests.WhenAllScholarlyAchievementsAreScored_ThenApplicationCanBeAccepted*
  attributes:
  - type: NUnit.Framework.TestAttribute
    ctor: NUnit.Framework.TestAttribute.#ctor
    arguments: []
- uid: CampusCrafterTests.ReviewApplicationTests.WhenNotAllScholarlyAchievementsAreScored_ThenApplicationCannotBeAccepted
  commentId: M:CampusCrafterTests.ReviewApplicationTests.WhenNotAllScholarlyAchievementsAreScored_ThenApplicationCannotBeAccepted
  id: WhenNotAllScholarlyAchievementsAreScored_ThenApplicationCannotBeAccepted
  parent: CampusCrafterTests.ReviewApplicationTests
  langs:
  - csharp
  - vb
  name: WhenNotAllScholarlyAchievementsAreScored_ThenApplicationCannotBeAccepted()
  nameWithType: ReviewApplicationTests.WhenNotAllScholarlyAchievementsAreScored_ThenApplicationCannotBeAccepted()
  fullName: CampusCrafterTests.ReviewApplicationTests.WhenNotAllScholarlyAchievementsAreScored_ThenApplicationCannotBeAccepted()
  type: Method
  source:
    remote:
      path: CampusCrafterTests/ReviewApplicationTests.cs
      branch: monczak
      repo: https://github.com/CampusCrafter/campuscrafter
    id: WhenNotAllScholarlyAchievementsAreScored_ThenApplicationCannotBeAccepted
    path: CampusCrafterTests/ReviewApplicationTests.cs
    startLine: 108
  assemblies:
  - CampusCrafterTests
  namespace: CampusCrafterTests
  syntax:
    content: >-
      [Test]

      public Task WhenNotAllScholarlyAchievementsAreScored_ThenApplicationCannotBeAccepted()
    return:
      type: System.Threading.Tasks.Task
    content.vb: >-
      <Test>

      Public Function WhenNotAllScholarlyAchievementsAreScored_ThenApplicationCannotBeAccepted() As Task
  overload: CampusCrafterTests.ReviewApplicationTests.WhenNotAllScholarlyAchievementsAreScored_ThenApplicationCannotBeAccepted*
  attributes:
  - type: NUnit.Framework.TestAttribute
    ctor: NUnit.Framework.TestAttribute.#ctor
    arguments: []
references:
- uid: CampusCrafterTests
  commentId: N:CampusCrafterTests
  href: CampusCrafterTests.html
  name: CampusCrafterTests
  nameWithType: CampusCrafterTests
  fullName: CampusCrafterTests
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: CampusCrafterTests.ReviewApplicationTests.Setup*
  commentId: Overload:CampusCrafterTests.ReviewApplicationTests.Setup
  href: CampusCrafterTests.ReviewApplicationTests.html#CampusCrafterTests_ReviewApplicationTests_Setup
  name: Setup
  nameWithType: ReviewApplicationTests.Setup
  fullName: CampusCrafterTests.ReviewApplicationTests.Setup
- uid: System.Threading.Tasks.Task
  commentId: T:System.Threading.Tasks.Task
  parent: System.Threading.Tasks
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task
  name: Task
  nameWithType: Task
  fullName: System.Threading.Tasks.Task
- uid: System.Threading.Tasks
  commentId: N:System.Threading.Tasks
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Threading.Tasks
  nameWithType: System.Threading.Tasks
  fullName: System.Threading.Tasks
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Threading
    name: Threading
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading
  - name: .
  - uid: System.Threading.Tasks
    name: Tasks
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Threading
    name: Threading
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading
  - name: .
  - uid: System.Threading.Tasks
    name: Tasks
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks
- uid: CampusCrafterTests.ReviewApplicationTests.WhenAllScholarlyAchievementsAreScored_ThenApplicationCanBeAccepted*
  commentId: Overload:CampusCrafterTests.ReviewApplicationTests.WhenAllScholarlyAchievementsAreScored_ThenApplicationCanBeAccepted
  href: CampusCrafterTests.ReviewApplicationTests.html#CampusCrafterTests_ReviewApplicationTests_WhenAllScholarlyAchievementsAreScored_ThenApplicationCanBeAccepted
  name: WhenAllScholarlyAchievementsAreScored_ThenApplicationCanBeAccepted
  nameWithType: ReviewApplicationTests.WhenAllScholarlyAchievementsAreScored_ThenApplicationCanBeAccepted
  fullName: CampusCrafterTests.ReviewApplicationTests.WhenAllScholarlyAchievementsAreScored_ThenApplicationCanBeAccepted
- uid: CampusCrafterTests.ReviewApplicationTests.WhenNotAllScholarlyAchievementsAreScored_ThenApplicationCannotBeAccepted*
  commentId: Overload:CampusCrafterTests.ReviewApplicationTests.WhenNotAllScholarlyAchievementsAreScored_ThenApplicationCannotBeAccepted
  href: CampusCrafterTests.ReviewApplicationTests.html#CampusCrafterTests_ReviewApplicationTests_WhenNotAllScholarlyAchievementsAreScored_ThenApplicationCannotBeAccepted
  name: WhenNotAllScholarlyAchievementsAreScored_ThenApplicationCannotBeAccepted
  nameWithType: ReviewApplicationTests.WhenNotAllScholarlyAchievementsAreScored_ThenApplicationCannotBeAccepted
  fullName: CampusCrafterTests.ReviewApplicationTests.WhenNotAllScholarlyAchievementsAreScored_ThenApplicationCannotBeAccepted
